### ISSUE TITLE
Tauri Dev sidecar not starting and crash

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-dashboard#176]
MacBook Pro M1
OS: MacOS Monterey 

Changing `rpc_proxy.go` with `resp.Header().Set("Access-Control-Allow-Origin", "http://localhost:3003")`

When running `cargo tauri dev` the sidecar doesn't start. 
We can start it from `src-tauri/bin/grpcproxy-aarch64-apple-darwin`.
However it quickly crashes.
```
INFO[0000] start listening on :3030                 
INFO[0004] handling gRPC web request: /Operator/ListMarkets 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x240 pc=0x10275b160]

goroutine 23 [running]:
google.golang.org/grpc.(*ClientConn).NewStream(0x0, {0x1029760b8, 0x140000b23c0}, 0x102cca9c0, {0x140000ae095, 0x15}, {0x0, 0x0, 0x0})
	/Users/stephane/go/pkg/mod/google.golang.org/grpc@v1.42.0/stream.go:153 +0x20
google.golang.org/grpc.NewClientStream(...)
	/Users/stephane/go/pkg/mod/google.golang.org/grpc@v1.42.0/stream.go:163
github.com/mwitkow/grpc-proxy/proxy.(*handler).handler(0x1400000e268, {0x0, 0x0}, {0x10297a8e8, 0x140000e00c0})
	/Users/stephane/go/pkg/mod/github.com/mwitkow/grpc-proxy@v0.0.0-20181017164139-0f1106ef9c76/proxy/handler.go:74 +0x120
google.golang.org/grpc.(*Server).processStreamingRPC(0x14000021500, {0x10297e2e0, 0x140000c43f0}, 0x140000e6000, 0x0, 0x140001184c0, 0x0)
	/Users/stephane/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1540 +0xf44
google.golang.org/grpc.(*Server).handleStream(0x14000021500, {0x10297e2e0, 0x140000c43f0}, 0x140000e6000, 0x0)
	/Users/stephane/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1626 +0x9a4
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400009e210, 0x14000021500, {0x10297e2e0, 0x140000c43f0}, 0x140000e6000)
	/Users/stephane/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:921 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/stephane/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:919 +0x1f0

Saving session...completed.

[Process completed]
``` 

Running `yarn tauri:build --debug` and changing `rpc_proxy.go` with `resp.Header().Set("Access-Control-Allow-Origin", "tauri://localhost:3003")` works fine.

**Comment by tiero** [comment]
We should eventually have a flag to restrict the URL of the caller/client

**Comment by Janaka-Steph** [comment]
Actually it's normal that running `cargo tauri dev` the sidecar doesn't start. Need to add it in `beforeDevCommand` of tauri.conf.json

**Comment by tiero** [comment]
Shall we use * ?
